### PR TITLE
Try to fix #49

### LINKED ISSUE #49: When deploying to heroku, mongodb by mlab url is not set to DATABASE_URI
Cause:

When deploying to heroku, mongodb env of mlab is named MONGODB_URI, but the parse server expects url from DATABASE_URI. So users will encounter error access to mongodb from localhost of heroku app, this makes client not able to read or write any data.

Solution:

1. Manually set DATABASE_URI to content of MONGODB_URI
2. Try read MONGODB_URI when deploying to heroku

Br,
Nick

### PR DESCRIPTION
**Pull request by vmlinz**
Try to fix #49 

Update index.js

### CODE REVIEW

**Comment by yongjhih** [comment]
Would you please resolve conflicts, I'll merge it.

**Comment by vmlinz** [comment]
Sorry for that, I will clean it up.

**Comment by yongjhih** [comment]
It's ok, thanks for your cooperation.

**Comment by vmlinz** [comment]
PR rebased to master branch, please refer to #51 

I am going to close this PR.

Nick

**Pull request closed without merging**
