### PR TITLE
Bring server up to 2.2.10

### PR DESCRIPTION
**Pull request by r2DoesInc**

### CODE REVIEW

**Comment by yongjhih** [comment]
If you want to get 2.2.10  version, I can refresh docker hub for images building with all released npm.

**Comment by r2DoesInc** [comment]
Cool. I'm just using a locally built one from that pr right now,.

**Comment by yongjhih** [comment]
This project is as launcher for parse-server npm, so i think it's unnecessary merged with ParsePlaftfrom/parse-server. But I'll consider about merging if resolved conflicts.

**Comment by jeveloper** [comment]
@yongjhih this needs to be closed :)

**Pull request closed without merging**
